version: '3.7'
services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        container_name: phpmyadmin
        ports:
            - 80:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=godev
        depends_on:
            - mysql
        links:
            - mysql

    mysql:
        image: mysql:5.7
        container_name: database
        ports:
            - 3306:3306
        volumes:
            - "$PWD/data/db:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD=godev

    redis:
        image: redis:alpine3.11
        container_name: cache
        ports:
            - 6379:6379

    rabbitmq:
        image: rabbitmq:3-management
        container_name: queue
        hostname: my-rabbit
        volumes:
            - "$PWD/data/queue:/var/lib/rabbitmq"
        ports:
            - 8080:15672
            - 5672:5672
            # - 25676:25676        
        # deploy:
        #     resources:
        #         limits:
        #             memory: 4096M
        #         reservations:
        #             memory: 2048M