version: '3.7'
services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        container_name: phpmyadmin
        ports:
            - 80:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=godev
        depends_on:
            - mysql
        links:
            - mysql

    mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
            - 3306:3306
        volumes:
            - "$PWD/data:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD=godev

    redis:
        image: redis:alpine3.11
        container_name: redis
        ports:
            - 6379:6379